language: node_js

node_js: 8

install:
  - yarn

script:
  - yarn run lint
  - yarn run test
  - cat ./coverage/lcov.info | npx coveralls
  - yarn run compile

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    tags: false
    branch: master
    repo: freelyformd/mq
